site_name: Acai JS
site_url: https://syngenta.github.io/acai-js-docs
site_author: Paul Cruse III
site_dir: ../docs
nav:
    - Home: index.md
    - Tutorials:
        - demo.md
    - install.md
    - Event Handlers:
        - APIGateway:
            - apigateway/index.md
            - Router:
                - apigateway/router/setup.md
                - apigateway/router/configurations.md
            - EndPoint:
                - apigateway/endpoint/setup.md
                - apigateway/endpoint/configurations.md
            - apigateway/request.md
            - apigateway/response.md
        - DynamoDB:
            - dynamodb/index.md
            - dynamodb/configurations.md
            - dynamodb/record.md
        - S3:
            - s3/index.md
            - s3/configurations.md
            - s3/record.md
        - SNS/SQS:
            - sqs/index.md
            - sqs/configurations.md
            - sqs/record.md
    - common/logger.md
    - changes.md
    - NPM Registry: https://www.npmjs.com/package/@syngenta-digital/alc
    - Github Repository: https://github.com/syngenta/acai-js
    - Issues: https://github.com/syngenta/acai-js/issues
theme:
    name: material
    logo: https://avatars.githubusercontent.com/u/65528694?s=200&v=4
    palette:
        -
            media: "(prefers-color-scheme: light)"
            scheme: syngenta-light
    highlightjs: true
    hljs_languages:
        - python
        - javascript
        - yml
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    features:
        - navigation.top
        - navigation.instant
        - navigation.indexes
        - navigation.tracking
        - content.code.annotate
markdown_extensions:
    - codehilite
    - meta
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
        linenums: true
    - pymdownx.snippets:
        base_path: "."
        check_paths: true
    - toc:
        permalink: true
        toc_depth: 4
    - pymdownx.superfences:
        custom_fences:
            -
                name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
    - search
    - markdownextradata
    - mkdocs-video
extra:
    web:
        url: https://syngenta.github.io/acai-js-docs
extra_css:
    - extra.css

### colors ###
# blue: #01004C
# green: #70D979
# text: white
# dark mode:
    # bg: blue
    # text: white
    # links: green
# light mode:
    # bg: white
    # text: blue
    # links: green
