components:
    schemas:
        sqs-record:
            title: sqs-record
            type: object
            properties:
                id:
                    type: string
                body:
                    type: object
