service: sns-sqs-example
package:
    exclude:
        - .*
        - .**/**
        - aws/**
        - test/**
        - README.md
        - serverless.yml
        - package.json
        - package-lock.json
custom:
    logRetentionInDays: 1
provider:
    name: aws
    runtime: nodejs14.x
    versionFunctions: false
    endpointType: regional
    profile: global-poc
    stage: poc
    region: us-east-1
    stackName: ${self:provider.stackTags.name}
    deploymentBucket:
        name: ${self:provider.stage}-${self:provider.region}-alc-examples
    stackTags:
        name: ${self:provider.stage}-${self:service}
        service: ${self:service}
        environment: ${self:provider.stage}
        managed-by: serverless
    iam:
        role:
            statements:
                - ${file(./aws/iamroles/sns.yml)}
                - ${file(./aws/iamroles/sqs.yml)}
resources:
    - ${file(./aws/resources/sns.yml)}
    - ${file(./aws/resources/sns-subscription.yml)}
    - ${file(./aws/resources/sqs.yml)}
    - ${file(./aws/resources/sqs-policy.yml)}
functions:
    v1-sqs-event-handler:
        name: ${self:provider.stackTags.name}-v1-sqs-event-handler
        handler: sqs/handler.listen
        description: example sqs handler
        memorySize: 256
        events:
            - sqs:
                batchSize: 1
                arn:
                    Fn::GetAtt: [ExampleQueue, Arn]
plugins:
    - serverless-plugin-bind-deployment-id
    - serverless-plugin-log-retention
    - serverless-deployment-bucket
