Resources:
    ExampleSNS:
        Type: AWS::SNS::Topic
        Properties:
            DisplayName: ${self:provider.stackTags.name}
            TopicName: ${self:provider.stackTags.name}
            Tags:
                -
                    Key: Name
                    Value: ${self:provider.stackTags.name}
