Resources:
    ExampleQueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            Queues:
                - Ref: ExampleQueue
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: "Allow"
                        Principal: "*"
                        Action:
                            - sqs:CreateQueue
                            - sqs:DeleteMessage
                            - sqs:DeleteQueue
                            - sqs:GetQueueUrl
                            - sqs:ListQueues
                            - sqs:ReceiveMessage
                            - sqs:SendMessage
                        Resource:
                            - arn:aws:sqs:*:*:${self:provider.stackTags.name}
                        Condition:
                            StringEquals:
                                AWS:SourceAccount: !Ref AWS::AccountId
