service: s3-example
package:
    exclude:
        - .*
        - .**/**
        - aws/**
        - test/**
        - README.md
        - serverless.yml
        - package.json
        - package-lock.json
custom:
    logRetentionInDays: 1
provider:
    name: aws
    runtime: nodejs14.x
    versionFunctions: false
    endpointType: regional
    profile: global-poc
    stage: poc
    region: us-east-1
    stackName: ${self:provider.stackTags.name}
    deploymentBucket:
        name: ${self:provider.stage}-${self:provider.region}-alc-examples
    stackTags:
        name: ${self:provider.stage}-${self:service}
        service: ${self:service}
        environment: ${self:provider.stage}
        managed-by: serverless
    iam:
        role:
            statements:
                - ${file(./aws/iamroles/s3.yml)}
    s3:
        data-bucket:
            name: ${self:provider.stackTags.name}-data
functions:
    v1-s3-event-handler:
        name: ${self:provider.stackTags.name}-v1-s3-event-handler
        handler: s3/handler.event
        description: example s3 handler
        memorySize: 256
        events:
            - s3:
                  bucket: data-bucket
                  event: s3:ObjectCreated:*
plugins:
    - serverless-plugin-bind-deployment-id
    - serverless-plugin-log-retention
    - serverless-deployment-bucket
