components:
    schemas:
        ddb-record:
            title: ddb-record
            type: object
            properties:
                id:
                    type: string
                body:
                    type: object
