service: dynamodb-example
package:
    exclude:
        - .*
        - .**/**
        - aws/**
        - test/**
        - README.md
        - serverless.yml
        - package.json
        - package-lock.json
custom:
    logRetentionInDays: 1
provider:
    name: aws
    runtime: nodejs14.x
    versionFunctions: false
    endpointType: regional
    profile: global-poc
    stage: poc
    region: us-east-1
    stackName: ${self:provider.stackTags.name}
    deploymentBucket:
        name: ${self:provider.stage}-${self:provider.region}-alc-examples
    stackTags:
        name: ${self:provider.stage}-${self:service}
        service: ${self:service}
        environment: ${self:provider.stage}
        managed-by: serverless
    iam:
        role:
            statements:
                - ${file(./aws/iamroles/dynamodb.yml)}
resources:
    - ${file(./aws/resources/dynamodb.yml)}
functions:
    v1-ddb-stream-handler:
        name: ${self:provider.stackTags.name}-v1-ddb-stream-handler
        handler: ddb/handler.stream
        description: example ddb handler
        memorySize: 256
        events:
            - stream:
                type: dynamodb
                arn:
                    Fn::GetAtt: [ExampleTable, StreamArn]
plugins:
    - serverless-plugin-bind-deployment-id
    - serverless-plugin-log-retention
    - serverless-deployment-bucket
